version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0
    ports:
      - "8188:8080"
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db-sma.chs2odnq0ipw.us-east-2.rds.amazonaws.com:5432/keycloack
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 123456jg
    command: 
      - start-dev 
      - --import-realm
    volumes:
      - /home/keycloak/realm.json:/opt/keycloak/data/import/realm.json 
